### PR TITLE
fix missing image bug by adding placeholder image

### LINKED ISSUE #3: #INC-5312: Missing image
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

### PR DESCRIPTION
**Pull request by EdwardTheLegend**
closes #3

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks EdwardTheLegend, I'll review the changes right away!

**Review by vanessa-cooper — DISMISSED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by EdwardTheLegend** [comment]
can you review again

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - I have no idea why, but I've been told that we are not allowed to update "docker-compose.yml". Please make sure to revert your changes before merging your PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job EdwardTheLegend! You're now able to merge the PR.

**Pull request merged**
